spring:
  config:
    activate:
      on-profile: dev

  datasource:
    primary:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
      validationQuery: select 1
      test-on-borrow: true
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

logging:
  config: classpath:log4j2-dev.xml